import type {Metadata} from "next";
import {ReactNode} from "react";
import "./styles/globals.scss";
import './styles/reset.scss';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Providers from "@/app/providers";

export const metadata: Metadata = {
    title: "Dice Game",
    description: "Generated by create next app, edited by MoMoT",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
